framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: assethub/app
        
        # Use Redis if available, fallback to filesystem
        app: 'cache.adapter.redis'
        default_redis_provider: 'redis://localhost:6379/0'
        
        pools:
            # Cache dla ustawień systemu
            cache.settings:
                adapter: cache.adapter.redis
                default_lifetime: 3600  # 1 hour
                
            # Cache dla sesji użytkowników  
            cache.sessions:
                adapter: cache.adapter.redis
                default_lifetime: 86400  # 24 hours
                
            # Cache dla uprawnień użytkowników
            cache.permissions:
                adapter: cache.adapter.redis  
                default_lifetime: 1800   # 30 minutes
                
            # Cache dla danych LDAP
            cache.ldap:
                adapter: cache.adapter.redis
                default_lifetime: 900    # 15 minutes

when@dev:
    framework:
        cache:
            # W środowisku dev używaj filesystem cache
            app: 'cache.adapter.filesystem'

when@test:
    framework:
        cache:
            app: 'cache.adapter.array'
