monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - security    # Security-related events
        - app         # Application-specific logs
        - doctrine    # Database operations
        - equipment   # Equipment module logs
        - dictionary  # Dictionary system logs

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: info
                channels: [security]
            app:
                type: stream
                path: "%kernel.logs_dir%/app.log"
                level: debug
                channels: [app]
            doctrine:
                type: stream
                path: "%kernel.logs_dir%/doctrine.log"
                level: debug
                channels: [doctrine]
            equipment:
                type: stream
                path: "%kernel.logs_dir%/equipment.log"
                level: debug
                channels: [equipment]
            dictionary:
                type: stream
                path: "%kernel.logs_dir%/dictionary.log"
                level: debug
                channels: [dictionary]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: debug
                channels: [security]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation.log"
                formatter: monolog.formatter.json
