parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Rate limiter factories
    App\Security\LdapAuthenticator:
        arguments:
            $loginLimiter: '@limiter.login'
            
    # Search rate limiter 
    App\Controller\SearchController:
        arguments:
            $searchLimiter: '@limiter.search'
            
    # Settings cache
    App\Service\SettingService:
        arguments:
            $settingsCache: '@cache.settings'