parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Rate limiter factories
    App\Security\LdapAuthenticator:
        arguments:
            $loginLimiter: '@limiter.login'
            
    # Search rate limiter 
    App\Controller\SearchController:
        arguments:
            $searchLimiter: '@limiter.search'
            
    # Settings cache
    App\Service\SettingService:
        arguments:
            $settingsCache: '@cache.settings'
            
    # Authorization service with permissions cache
    App\Service\AuthorizationService:
        arguments:
            $permissionsCache: '@cache.permissions'
            
    # LDAP service with cache
    App\Service\LdapService:
        arguments:
            $ldapCache: '@cache.ldap'
            
    # Exception listener
    App\EventListener\ExceptionListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }